/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core';
import * as import1 from './index';
class IonicStorageModuleInjector extends import0.ɵNgModuleInjector<import1.IonicStorageModule> {
  _IonicStorageModule_0:import1.IonicStorageModule;
  constructor(parent:import0.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  createInternal():import1.IonicStorageModule {
    this._IonicStorageModule_0 = new import1.IonicStorageModule();
    return this._IonicStorageModule_0;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import1.IonicStorageModule)) { return this._IonicStorageModule_0; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const IonicStorageModuleNgFactory:import0.NgModuleFactory<import1.IonicStorageModule> = new import0.NgModuleFactory<any>(IonicStorageModuleInjector,import1.IonicStorageModule);